import React, { useEffect, useRef, useState } from 'react';
import styles from './styles/Layout.module.scss'
import Head from 'next/head';
import Image from 'next/image';
import ilwel from '../../public/ilwel.png'
import diamond from '../../public/diamond.svg'
import { useRouter } from 'next/router';
import Typewriter from 'typewriter-effect/dist/core';
// import fallen from '../../public/audio/fallen.mp3'

const Layout = ({children}) => {

  const router = useRouter()

  const audio = useRef(null)

  const [dialog, setDialog] = useState('')

  useEffect(() => {

    if(router.pathname === '/') setDialog('Olá, essa página foi feita para divulgar minha carreira como programador')
    if(router.pathname === '/projects') setDialog('Alguns dos meus projetos :)')

    var tp = document.getElementById('typewriter');

    var typewriter = new Typewriter(tp, {
      delay: 70,
      deleteSpeed: 2,
    });

    if(router.pathname === '/' && dialog){
      const phrase2 = 'Eu <strong>sempre</strong> quis um lugar na internet para chamar de meu'
      const phrase3 = 'Eu tenho um <strong>imenso</strong> amor por tecnologia e tudo o que ela me permite criar'
      const phrase4 = 'Quero estar <strong>sempre</strong> criando coisas novas e ir preenchendo esse cantinho com essas experiências <3.'
      typewriter
      .typeString(dialog)
      .pauseFor(600)
      .deleteChars(dialog.length)
      .typeString(phrase2)
      .pauseFor(600)
      .deleteChars(phrase2.length)
      .typeString(phrase3)
      .pauseFor(600)
      .deleteChars(phrase3.length)
      .typeString(phrase4)
      .pauseFor(600)
      .typeString(' Sinta-se em casa ^^')
      .start();
    }
    else{
      typewriter
        .typeString(dialog)
        .pauseFor(300)
        .start();
    }
    
  
  }, [dialog, router.pathname])

  const [isHover, setIsHover] = useState(0)

  const onClick = (to) => {
    if(to === 'projects'){
      router.push('/projects')
    }
  
  }

  return (
    <>
      <Head>
      <title>Ilwel</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
      <main className={styles['l-general']}>
        <Image className={styles['ilwel']} src={ilwel} alt='ilwel pixel art'/>
        <div className={styles['dialog-box']}>
          <div className='outlined'>
            <p id='typewriter'></p>
          </div>
        </div>
        <div className={styles['nav']}>
          <div className="outlined">

            <h2>Ilwel Isaac</h2>
            <p className='sub-text'>Desenvolvedor de Software</p>
            <ul>
              <li onClick={ () => onClick('projects')} onMouseEnter={() => setIsHover(1)} onMouseLeave={() => setIsHover(0)}>

                  <Image src={diamond} alt='diamond icon'/>

                <p>
                  Projetos
                </p>
              </li>
              <li onMouseEnter={() => setIsHover(2)} onMouseLeave={() => setIsHover(0)}>

                  <Image src={diamond} alt='diamond icon'/>

                <p>
                  Carreira
                </p>
              </li>
              <li onMouseEnter={() => setIsHover(3)} onMouseLeave={() => setIsHover(0)}>

                  <Image src={diamond} alt='diamond icon'/>

                <p>
                  Formação
                </p>
              </li>
            </ul>
          </div>
        </div>
        {children}
      </main>
    </>
  );
};

export default Layout;