export const tecnologies = [

  {name:'React', about: '<strong>React</strong> foi meu primeiro contato com uma forma moderna de desenvolver frontend. Foi o grande responsável por me possibilitar ver minhas ideias ganharem forma. Ocupa um espaço especial no meu coração por me abrir os olhos pra estudar desenvolvimento frontend e tudo que isso envolve (ux/ui, design, ilustração, etc).'},
  {name:'NodeJS', about: 'Sem <strong>NodeJS</strong> eu acredito que minha entrada no mercado de trabalho teria sido bem mais lenta. Ter a possibilidade de desenvolver em um mesmo eco sistema todas as etapas da sua aplicação (Frontend e Backend) usando a mesma linguagem foi uma mão na roda pra entender o básico de desenvolvimento web.'},
  {name:'Typescript', about: '<strong>Typescript</strong> é uma das minhas linguagens favoritas. Ela permitiu eu aproximar muito do que eu tinha aprendido em Desenvolvimento Orientado a Objeto ao meu dia a dia de desenvolvedor web. Em projetos pessoais eu tendo a escolher Typescript em vez de Javascript por abrir mais possibilidades de arquitetura e padrões de projeto.'},
  {name:'NextJS', about: '<strong>NextJS</strong> é uma ferramenta incrível! Soluções que seriam chatinhas de implementar na mão para melhorar performance de um site se tornam uma questão de poucas linhas. E a curva de aprendizado é muito rápida, principalmente pra quem vem do React.'},
  {name:'Graphql', about: '<strong>Graphql</strong> é uma abordagem que eu acredito que só vai aumentar de adesão a medida que encaminharmos para o futuro. Eu tive um grande e ambicioso projeto com uma quantidade massiva de dados com várias entidades e relações. Graphql simplificou muita coisa com uma sacada muito simples, além disso, tem um eco sistema muito forte em Typescript.'},
  {name:'Java', about: '<strong>Java</strong> foi uma das primeiras linguagens de programação que eu aprendi. Eu gosto da estética de um projeto em Java, POO é meu paradigma de programação favorito. As primeiras vezes que eu tentei desenvolver algum software com interface foi por causa do Java. É uma linguagem que marcou meus primeiros passos e também foi essencial para minha carreira.'},
  {name:'Spring Boot', about: '<strong>Spring Boot</strong> foi a ferramenta que me fez sair do Javascript por uns tempos. Desenvolver backend com Java me ensinou muita coisa. Tudo aquilo que eu tinha visto na faculdade sobre Orientação a Objeto, SOLID, Arquitetura, etc, começou a se encaixar nos projetos que eu desenvolvia em Spring. É uma ferramenta que eu sempre vou levar para projetos futuros.'},
  {name:'C++', about: '<strong>C e C++</strong> me ensinaram o básico de programação, foram literalmente meus primeiros passos em computação e tecnologia. Eu consigo lembrar dos estudos sobre estruturas de dados, alocação de memória, orientação a objeto, escopo, etc. Sem essas duas linguagens, eu não seria metade do programador que eu sou hoje.'},
  {name:'Python', about: '<strong>Python</strong> foi a primeira linguagem interpretada que eu aprendi. Eu me lembro do quanto era empolgante tudo o que você conseguia fazer com aquela sintaxe simples e elegante. Para mim que vinha de linguagens mais engessadas, escrever código em Python era muito divertido. Já fiz alguns projetos aqui e ali com Python e um dia pretendo me aprofundar onde essa linguagem tem força: IA.'},

]